const collegedata = [
  {
    "zip": "02481-5399",
    "school_url": "https://www.massbay.edu",
    "price_calculator_url": "https://mbccweb.massbay.edu/netpricecalculator/",
    "name": "Massachusetts Bay Community College",
    "size": 3496,
    "state": "MA",
    "id": 166647,
    "city": "Wellesley Hills"
  },
  {
    "zip": "02115-5882",
    "school_url": "www.massart.edu",
    "price_calculator_url": "massart.edu/net-price-calculator",
    "name": "Massachusetts College of Art and Design",
    "size": 1828,
    "state": "MA",
    "id": 166674,
    "city": "Boston"
  },
  {
    "2018.admissions.admission_rate.overall": 0.2789,
    "zip": "02467",
    "school_url": "www.bc.edu",
    "price_calculator_url": "https://npc.collegeboard.org/student/app/bc",
    "name": "Boston College",
    "size": 9639,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 650.0,
    "id": 164924,
    "city": "Chestnut Hill"
  },
  {
    "2018.admissions.admission_rate.overall": 0.9014,
    "zip": "02325",
    "school_url": "www.bridgew.edu",
    "price_calculator_url": "microsites.bridgew.edu/financialaid/net-price-calculator",
    "name": "Bridgewater State University",
    "size": 9312,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 500.0,
    "id": 165024,
    "city": "Bridgewater"
  },
  {
    "2018.admissions.admission_rate.overall": 0.1807,
    "zip": "02186",
    "school_url": "www.laboure.edu/about-labour-",
    "price_calculator_url": "www.laboure.edu/tuition-financial-aid/net-price-calculator",
    "name": "Laboure College",
    "size": 845,
    "state": "MA",
    "id": 165264,
    "city": "Milton",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.4146,
    "zip": "02445-7415",
    "school_url": "www.hchc.edu",
    "price_calculator_url": "www.hchc.edu/assets/files/FinancialAid/npcalc.htm",
    "name": "Hellenic College-Holy Cross Greek Orthodox School of Theology",
    "size": 65,
    "state": "MA",
    "id": 166054,
    "city": "Brookline",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.6747,
    "zip": "01013",
    "school_url": "https://www.elms.edu",
    "price_calculator_url": "https://tcc.noellevitz.com/(S(fwtmfnosjzw40vqinl1pafji))/Elms%20College/Freshman-Students",
    "name": "College of Our Lady of the Elms",
    "size": 1127,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 480.0,
    "id": 167394,
    "city": "Chicopee"
  },
  {
    "zip": "02135-3846",
    "school_url": "www.sjs.edu",
    "price_calculator_url": "www.sjs.edu",
    "name": "Saint John's Seminary",
    "size": 24,
    "state": "MA",
    "id": 167677,
    "city": "Brighton",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.7676,
    "zip": "02445",
    "school_url": "www.newbury.edu",
    "price_calculator_url": "www.newbury.edu/admissions-and-aid/financial-aid-and-billing/financial-aid/net-price-calculator",
    "name": "Newbury College",
    "size": 635,
    "state": "MA",
    "id": 167251,
    "city": "Brookline",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.6839,
    "zip": "01109",
    "school_url": "www.aic.edu",
    "price_calculator_url": "https://www.aic.edu/admissions/tuition-and-financial-aid/net-price-calculator/",
    "name": "American International College",
    "size": 1307,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 460.0,
    "id": 164447,
    "city": "Springfield"
  },
  {
    "2018.admissions.admission_rate.overall": 0.7978,
    "zip": "02466",
    "school_url": "www.lasell.edu/",
    "price_calculator_url": "www.lasell.edu/tuition-and-aid/net-price-calculator.html",
    "name": "Lasell University",
    "size": 1650,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 490.0,
    "id": 166391,
    "city": "Newton"
  },
  {
    "zip": "02155",
    "school_url": "www.lmregis.org",
    "price_calculator_url": "lmregis.org/wp-content/uploads/2019/11/Net-Price-Calculator.html",
    "name": "Lawrence Memorial Hospital School of Nursing",
    "size": 281,
    "state": "MA",
    "id": 166407,
    "city": "Medford",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "zip": "02129",
    "school_url": "www.cambridgecollege.edu",
    "price_calculator_url": "cambridgecollege.edu/net-price-calculator/",
    "name": "Cambridge College",
    "size": 690,
    "state": "MA",
    "id": 165167,
    "city": "Boston",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.7727,
    "zip": "02136-4030",
    "school_url": "Boston.edu",
    "price_calculator_url": "www.boston.edu/npc",
    "name": "Boston Baptist College",
    "size": 56,
    "state": "MA",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": 430.0,
    "id": 164614,
    "city": "Boston"
  },
  {
    "zip": "02668-1599",
    "school_url": "www.capecod.edu",
    "price_calculator_url": "www.capecod.edu/files/netprice/index.html",
    "name": "Cape Cod Community College",
    "size": 2544,
    "state": "MA",
    "id": 165194,
    "city": "West Barnstable",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.6927,
    "zip": "02116",
    "school_url": "www.baystate.edu",
    "price_calculator_url": "www.baystate.edu/financial-aid/tuition-fees/net-price-calculator/",
    "name": "Bay State College",
    "size": 684,
    "state": "MA",
    "id": 164641,
    "city": "Boston",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "zip": "01301-9739",
    "school_url": "www.gcc.mass.edu",
    "price_calculator_url": "web.gcc.mass.edu/financial-aid/net-price-calculator/",
    "name": "Greenfield Community College",
    "size": 1528,
    "state": "MA",
    "id": 165981,
    "city": "Greenfield",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "zip": "02116",
    "school_url": "www.bfit.edu/",
    "price_calculator_url": "www.bfit.edu/_forms/npcalc.htm",
    "name": "Benjamin Franklin Institute of Technology",
    "size": 550,
    "state": "MA",
    "id": 165884,
    "city": "Boston",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "zip": "01730-9124",
    "school_url": "https://www.middlesex.mass.edu",
    "price_calculator_url": "https://www.middlesex.mass.edu/netpricecalc/",
    "name": "Middlesex Community College",
    "size": 6620,
    "state": "MA",
    "id": 166887,
    "city": "Bedford",
    "2018.admissions.admission_rate.overall": null,
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  },
  {
    "2018.admissions.admission_rate.overall": 0.5939,
    "zip": "01610-1477",
    "school_url": "www.clarku.edu",
    "price_calculator_url": "www.clarku.edu/resources",
    "name": "Clark University",
    "size": 2252,
    "state": "MA",
    "id": 165334,
    "city": "Worcester",
    "2018.admissions.sat_scores.25th_percentile.critical_reading": null
  }
]
module.exports = collegedata
